### PR TITLE
Vologram WebGL player example

### PR DESCRIPTION
**Pull request by capnramses**
## Purpose of this PR

This PR adds a WebGL player example under the `examples/`.
This is intended as a reference implementation for playing volograms on the web, using the `vol_geom` library compiled to web assembly (WASM), paired with HTML5 video for decoding video textures.

* **99% of active code is in `index.html`**.
* there is a stub .js maths helper file (not important).
* generated `vol_geom.wasm` and generated `vol_geom.js` files (from emscripten). the `build.sh` file contains has the call to emscripten I used.
* the `wasm_vol_geom.c` is a wrapper for the `vol_geom.h` library to help emscripten generate the wasm interface JS file.

## Changes made in this PR

* Created `examples/04_vol_geom_wasm_webgl/` with minimal HTML and JavaScript (no frameworks or requirement to set up newer scripting).
* Minimal GLSL shaders are included in the HTML file under `<script>` tags.
* I didn't want to add a second set of shaders for volograms without per-vertex normals, but I left an example of how to use normals in the fragment shader, that can be easily hooked up.
* The `<video>` is shown below the canvas, and allows the user to debug the process, and also seek and pause into the vologram animation _via_ the video controls.
* ReadMe was updated to explain how to run the example, and what the new files are.
* Code in the example is somewhat minimised, and has comments explaining different sections.

## Testing Summary

To test this code

* The latest version is deployed here https://volograms.github.io/.
* Or, to test locally: run an HTTP server from the `examples/04_vol_geom_wasm_webgl/` directory. e.g. NPM's `http-server .`. And launch a web browser (anything except Firefox), and point it at the IP address indicated by the local server.

- [x] Explained how reviewers build, deploy, and test your code and what should they look for that would indicate a bug or regression.
- [x] Tested locally. Which platforms? OS/hardware/devices/compilers used.
- [x] Stated supported platforms have you not tested on, that you need help with?
- [ ] Named specific tools have you ran over the code: e.g. which { compilers, debuggers, fuzzers, profilers, sanitisers, linters, other tools }.
- [ ] Ran any unit tests that cover this code.
- [ ] Explained inputs used to test for bugs. e.g. existing known working data, large files, empty files, etc.

## Risk Introduced and any Breaking Changes

Provide more detail here as required.

- [ ] This PR introduces breaking changes (API or ABI). Instructions are provided for existing users to update their projects.
- [ ] This PR introduces new dependencies. You have provided links and licences in this section. This is **_extremely important!_**.
- [ ] New dependencies: Explained how any new dependencies are linked and built againt - .dll, inline code etc.?
- [ ] Gaps in testing: Is any code not covered by tests?
- [x] Gaps in testing: Are you unable to test on some platform? Or is some input data not available to you for testing?
- [ ] Analysed any other potential risks here.

## Pre-Merge Checklist

* If you have a problem with the review process (e.g. it's taking too long, or the reviewers forgot) get in touch with the Team Lead of the project!

- [x] Before making your PR, refresh your branch with a merge from its parent in case of conflicting changes since you started your branch.
- [x] This PR description is written clearly so that reviewers can understand the why/what/how of the work done.
- [x] Reviewed your own PR and checked your changed code.
- [x] Invited a range of good reviewers.
- [ ] Wait for a PR to be properly reviewed. Responded to all questions, and made any required changes.
- [ ] Received one other reviewer's approval. Ideally wait for 2+ approvals, especially if you didn't get a thorough reivew on the first approval.
- [ ] If a reviewer asks a question, even if you have another approval, got the approval of the other reviewers as well before merging.
- [ ] Made sure existing reviewers approved any changes to the PR.
- [ ] Resolved any merge conflicts after making the PR.
- [ ] CI/CD builds are not reporting any errors.

### CODE REVIEW

**Comment by capnramses** [comment]
tested on Brave and Chrome on Ubuntu Linux and Windows 10.

**Comment by capnramses** [comment]
fixed a bug found by @patrick-volograms where i had an incorrect "script type=module". this meant that whether or not the wasm loaded was kind of random

**Review by patrick-volograms — APPROVED** [review]
Tested, works perfectly

**Comment by capnramses** [comment]
i put it up live here https://volograms.github.io/ to make testing easier

i do get the occasional desync flicker on Safari iOS, but mostly it's okay.

i think i need to fix the MIME type on the video to stop it going fullscreen on iOS

**Comment by capnramses** [comment]
> i put it up live here https://volograms.github.io/ to make testing easier
> 
> i do get the occasional desync flicker on Safari iOS, but mostly it's okay.
> 
> i think i need to fix the MIME type or add "playsinline" on the video to stop it going fullscreen on iOS

done. tested. works with `playsinline`

**Review by patrick-volograms — APPROVED** [review]
Tested on both localhost and github.io, both work great

**Comment by capnramses** [comment]
> Tested on both localhost and github.io, both work great Also tested on iPad. Inline video works

thankyou !

**Pull request merged**
